import { Instrument_Serif, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const instrument = Instrument_Serif({
  variable: "--font-instrument",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const EditorialNew = localFont({
//   variable: "--font-editorialnew",
//   src: "../../../public/fonts/EditorialNew-Regular.otf",
//   weight: "400",
// });

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body className={instrument.className}>{children}</body>
    </html>
  );
}
